Updates userControllers status code for Update and Delete
mattfeg/rails-01 pull request #5
Opened 2024-12-20 13:11 UTC by mattfeg

Updates userControllers status code for Update and Delete.
Updates userControllers tests for changes.

2024-12-20 14:31 UTC, edimossilva commented on coverage/.last_run.json
> +    "line": 80.95
Add this file to gitignore

2024-12-20 14:31 UTC, edimossilva commented on coverage/.resultset.json
> +      "/Users/ferreira/Repositories/rails-01/app/controllers/users_controller.rb": {
Add this file to gitignore

2024-12-20 14:32 UTC, edimossilva commented on app/controllers/users_controller.rb
> +    if @user
the code for not_found is being duplicated at these 2 methods, please refactor in a way that you will not need to duplicate it

2024-12-20 14:32 UTC, edimossilva commented on app/controllers/users_controller.rb
> +        render json: @user, status: :no_content
you can return an empty hash instead of a user here

2024-12-20 14:33 UTC, edimossilva requested changes
Add specs to cover every single change you made

2024-12-22 02:43 UTC, mattfeg commented on coverage/.last_run.json
> +    "line": 80.95
Resolved on PR #6

2024-12-22 02:44 UTC, mattfeg commented on coverage/.resultset.json
> +      "/Users/ferreira/Repositories/rails-01/app/controllers/users_controller.rb": {
Resolved on PR #6

2024-12-22 13:15 UTC, edimossilva requested changes
Add specs to not found for update and destroy methods

2024-12-23 21:56 UTC, edimossilva commented on spec/controllers/user_controller_spec.rb
> +      allow(User).to receive(:find_by).and_return(user)
remove all mocks from these specs, mocks should be used for complex stuff

2024-12-26 11:52 UTC, merged