Implements user search on Index
mattfeg/rails-01 pull request #6
Opened 2024-12-20 14:15 UTC by mattfeg

Index can now return users that matches with param `name`.
Send a name for search as body params on index.
Exemple:
`{"name":"ABC"}`

2024-12-20 14:19 UTC, edimossilva commented on app/controllers/users_controller.rb
> +    searched_user = params[:name]
search_user_params is a better name

2024-12-20 14:20 UTC, edimossilva commented on app/controllers/users_controller.rb
> +      filtered_users = @users.select { |user| user.name.downcase.include?(searched_user.downcase) }
extract this filter to a scope and make it at db level

2024-12-20 14:21 UTC, edimossilva commented on app/controllers/users_controller.rb
> +        render json: { message: "Not found user" }, status: :not_found
we dont need not_found here, not found should be only at the show method, probably I confused myself when requested this to you or you missunderstood.

2024-12-20 14:22 UTC, edimossilva requested changes
- Fixes from my commments
- Add specs

2024-12-22 02:53 UTC, mattfeg reviewed
Fixes and tests requested done.

2024-12-22 13:17 UTC, edimossilva approved these changes

2024-12-23 12:04 UTC, merged